// GENERATED by @edgedb/generate v0.4.1

import * as $ from "../reflection";
import * as _ from "../imports";
import type * as _std from "./std";
import type * as _auth from "./ext/auth";
export type $IngredientλShape = $.typeutil.flatten<_std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588λShape & {
  "description": $.PropertyDesc<_std.$str, $.Cardinality.AtMostOne, false, false, false, false>;
  "name": $.PropertyDesc<_std.$str, $.Cardinality.One, false, false, false, false>;
}>;
type $Ingredient = $.ObjectType<"default::Ingredient", $IngredientλShape, null, [
  ..._std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588['__exclusives__'],
]>;
const $Ingredient = $.makeType<$Ingredient>(_.spec, "5aa9ffc4-446c-11ee-944a-272d7b133c79", _.syntax.literal);

const Ingredient: $.$expr_PathNode<$.TypeSet<$Ingredient, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($Ingredient, $.Cardinality.Many), null);

export type $RecipeλShape = $.typeutil.flatten<_std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588λShape & {
  "description": $.PropertyDesc<_std.$str, $.Cardinality.One, false, false, false, false>;
  "name": $.PropertyDesc<_std.$str, $.Cardinality.One, false, false, false, false>;
  "ingredients": $.LinkDesc<$RecipeIngredient, $.Cardinality.Many, {}, false, false,  false, false>;
}>;
type $Recipe = $.ObjectType<"default::Recipe", $RecipeλShape, null, [
  ..._std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588['__exclusives__'],
]>;
const $Recipe = $.makeType<$Recipe>(_.spec, "5aad67f6-446c-11ee-a776-3f977aa41949", _.syntax.literal);

const Recipe: $.$expr_PathNode<$.TypeSet<$Recipe, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($Recipe, $.Cardinality.Many), null);

export type $RecipeIngredientλShape = $.typeutil.flatten<$IngredientλShape & {
  "quantity": $.PropertyDesc<_std.$decimal, $.Cardinality.AtMostOne, false, false, false, false>;
  "unit": $.PropertyDesc<_std.$str, $.Cardinality.One, false, false, false, false>;
  "<ingredients[is Recipe]": $.LinkDesc<$Recipe, $.Cardinality.Many, {}, false, false,  false, false>;
  "<ingredients": $.LinkDesc<$.ObjectType, $.Cardinality.Many, {}, false, false,  false, false>;
}>;
type $RecipeIngredient = $.ObjectType<"default::RecipeIngredient", $RecipeIngredientλShape, null, [
  ...$Ingredient['__exclusives__'],
]>;
const $RecipeIngredient = $.makeType<$RecipeIngredient>(_.spec, "5aab8bbe-446c-11ee-bac1-9384483d1c77", _.syntax.literal);

const RecipeIngredient: $.$expr_PathNode<$.TypeSet<$RecipeIngredient, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($RecipeIngredient, $.Cardinality.Many), null);

export type $UserλShape = $.typeutil.flatten<_std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588λShape & {
  "identity": $.LinkDesc<_auth.$Identity, $.Cardinality.One, {}, true, false,  false, false>;
  "avatar": $.PropertyDesc<_std.$str, $.Cardinality.AtMostOne, false, false, false, false>;
  "email": $.PropertyDesc<_std.$str, $.Cardinality.AtMostOne, false, false, false, false>;
  "is_admin": $.PropertyDesc<_std.$bool, $.Cardinality.One, false, false, false, true>;
  "name": $.PropertyDesc<_std.$str, $.Cardinality.AtMostOne, false, false, false, false>;
}>;
type $User = $.ObjectType<"default::User", $UserλShape, null, [
  ..._std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588['__exclusives__'],
  {identity: {__element__: _auth.$Identity, __cardinality__: $.Cardinality.One | $.Cardinality.AtMostOne },},
]>;
const $User = $.makeType<$User>(_.spec, "f1285536-6220-11ee-a28c-599cb3829120", _.syntax.literal);

const User: $.$expr_PathNode<$.TypeSet<$User, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($User, $.Cardinality.Many), null);

export type $currentUserλShape = $.typeutil.flatten<$UserλShape & {
}>;
type $currentUser = $.ObjectType<"default::currentUser", $currentUserλShape, null, [
  ...$User['__exclusives__'],
]>;
const $currentUser = $.makeType<$currentUser>(_.spec, "e177edaf-c7b9-11ee-9421-690b29a734e6", _.syntax.literal);

const currentUser: $.$expr_PathNode<$.TypeSet<$currentUser, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($currentUser, $.Cardinality.Many), null);

const $default__globals: {  currentUser: _.syntax.$expr_Global<
              // "default::currentUser",
              $currentUser,
              $.Cardinality.AtMostOne
              >} = {  currentUser: _.syntax.makeGlobal(
              "default::currentUser",
              $.makeType(_.spec, "e177edaf-c7b9-11ee-9421-690b29a734e6", _.syntax.literal),
              $.Cardinality.AtMostOne) as any};



export { $Ingredient, Ingredient, $Recipe, Recipe, $RecipeIngredient, RecipeIngredient, $User, User, $currentUser, currentUser };

type __defaultExports = {
  "Ingredient": typeof Ingredient;
  "Recipe": typeof Recipe;
  "RecipeIngredient": typeof RecipeIngredient;
  "User": typeof User;
  "currentUser": typeof currentUser;
  "global": typeof $default__globals
};
const __defaultExports: __defaultExports = {
  "Ingredient": Ingredient,
  "Recipe": Recipe,
  "RecipeIngredient": RecipeIngredient,
  "User": User,
  "currentUser": currentUser,
  "global": $default__globals
};
export default __defaultExports;
